server:
  port: 10201
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.111.32.119:1521/helowinXDB
    username: test
    password: test
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  #配置别名包路径
  type-aliases-package: com.example.entity
  configuration:
    #日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰转换
    map-underscore-to-camel-case: true
