jasypt:
  encryptor:
    password: whaleleader
spring:
  datasource:
    username: root
    password: ENC(egcxqaMeNuzD0I3jVPytQA==)
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.zyy.entity

